plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - spiritualtablets.com.md
  - TheRosettaStoneforSiddhaAndAyurveda.md

theme: jekyll-theme-cayman
title: PreFit's homepage
description1: Bookmark this to keep an eye on project updates!
